name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  testsuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']
        prefer-lowest: ['']
        thumber-driver: ['imagick', 'gd']
        include:
          - php-version: '8.1'
            prefer-lowest: 'prefer-lowest'
            thumber-driver: 'imagick'
          - php-version: '8.2'
            prefer-lowest: 'prefer-lowest'
            thumber-driver: 'imagick'
          - php-version: '8.1'
            thumber-driver: 'gd'

    steps:
        - uses: actions/checkout@v3

        - name: Validate composer.json and composer.lock
          run: composer validate --strict

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            extensions: mbstring, intl, pdo_${{ matrix.db-type }}

        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v3
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-

        - name: Composer install
          run: |
            if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
              composer update --prefer-lowest --prefer-stable
            else
              composer update
            fi

        - name: Composer show
          run: composer show

        - name: Run PHPUnit
          env:
            THUMBER_DRIVER: ${{ matrix.thumber-driver }}
          run: |
            if  [[ ${{ matrix.thumber-driver }} == 'gd' ]] || ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
              vendor/bin/phpunit --exclude-group imageEquals
            elif [[ ${{ matrix.php-version }} == '8.0' ]]; then
             export XDEBUG_MODE=coverage && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
            else
              vendor/bin/phpunit
            fi

        - name: Submit code coverage
          if: matrix.php-version == '8.2'
          uses: codecov/codecov-action@v3

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            coverage: none
            tools: cs2pr

        - name: Composer install
          run: composer update

        - name: Composer show
          run: composer show

        - name: Run PHP CodeSniffer
          continue-on-error: true
          run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

        - name: Show PHPCS results in PR
          run: cs2pr ./phpcs-report.xml

        - name: Run psalm
          if: success() || failure()
          run: vendor/bin/psalm --output-format=github --php-version=8.2

        - name: Run phpstan
          if: success() || failure()
          run: vendor/bin/phpstan analyse --error-format=github


  testsuite-windows:
    runs-on: windows-2019
    name: Windows - PHP 8.2

    env:
      EXTENSIONS: mbstring, intl, gd
      PHP_VERSION: '8.2'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        ini-values: apc.enable_cli = 1, extension = php_fileinfo.dll
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Composer install
      run: composer update

    - name: Run PHPUnit
      run: vendor/bin/phpunit --verbose --exclude-group imageEquals
